### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by joykalyanguru** [skipperbent/pecee-http-service#22]
hi, Thanks for awesome framework.
If it's can be used with proxy, it would be more useful.

how can I use proxy with tinder-php-sdk or happn-php-sdk?

thanks in advance.

**Comment by skipperbent** [comment]
Hi @joyahm .

No problem - I'm glad that you are finding it useful.

You have to add a proxy option to curl. 

In the `HttpRequest` object use `addOption` to add the `CURLOPT_PROXY` option (you might also need `CURLOPT_PROXY_SERVICE_NAME` and `CURLOPT_PROXYUSERPWD` depending on your setup - more info here: http://php.net/manual/en/function.curl-setopt.php).

**Example:**

```php
$restBase->getHttpRequest()->addOption(CURLOPT_PROXY, '127.0.0.1:8080');
```

Depending on how the framework is constructed, you might have to overwrite the class itself it it resets the request object on each api call.

Thanks for taking the time to come with your feedback, I really appreciate it.

/ Simon

**Comment by joyahm** [comment]
sorry for delay, I've added this to api function on tinder.php.
```
$this->httpRequest->addOption([
          CURLOPT_PROXY, $proxy_host,
          CURLOPT_PROXYPORT, $proxy_port,
]);
```
and
`public function api($url = null, $method = self::METHOD_GET, array $data = [], $proxy_host, $proxy_port)`

now on my script (e.g. index.php)
$tinder = new \Pecee\Http\Service\Tinder($token_fb, $row['token_value'],$proxy_host,$proxy_port);

please let me know If I'm correct.

as a newbe, I'm afraid I've messed up. thanks for help.

**Comment by skipperbent** [comment]
Hi @joyahm .

I won't recommend that you create local changes to the library as these changes will break when a new update is available or when you are deploying on another environment.

Instead you should create your own class which extends the `\Pecee\Http\Service\Tinder` and from there make the changes to the `api` method.

Create something like this in your local project:

```php
class ProxyTinder extends \Pecee\Http\Service\Tinder 
{

	protected $proxyHost;
	protected $proxyPort;

	/**
     * @param null $url
     * @param string $method
     * @param array $data
     * @return Object
     * @throws \Pecee\Http\Rest\RestException
     */
    public function api($url = null, $method = self::METHOD_GET, array $data = [])
    {
	$options = [
            CURLOPT_SSL_VERIFYHOST => false,
            CURLOPT_SSL_VERIFYPEER => false,
        ];
		
		if($this->proxyHost !== null) {
			$options[CURLOPT_PROXY] = $this->proxyHost;
		}
		
		if($this->proxyPort !== null) {
			$options[CURLOPT_PROXYPORT] = $this->proxyPort;
		}
	
        $this->httpRequest->setOptions($options);
        $this->httpRequest->setPostJson(true);
        $this->httpRequest->setHeaders([
            'X-Auth-Token: ' . $this->authToken,
            'Content-type: application/json',
            'app_version: 3',
            'platform: ios',
            'User-Agent: Tinder/3.0.4 (iPhone; iOS 7.1; Scale/2.00)',
            'os_version: 700001',
        ]);
		
        return json_decode(parent::api($url, $method, $data)->getResponse());
    }
	
	/**
     * @param string $host
     * @return self
     * @throws \Pecee\Http\Rest\RestException
     */
	public function setProxyHost($host) 
	{
		$this->proxyHost = $host;
		return $this;
	}
	
	/**
     * @param int $port
     * @return self
     * @throws \Pecee\Http\Rest\RestException
     */
	public function setProxyPort($port) 
	{
		$this->proxyPort = $port;
		return $this;
	}

}
```

and then call it like this:

```php
$tinder = new ProxyTinder($token_fb, $row['token_value']);
$tinder->setProxyHost('127.0.0.1');
$tinder->setProxyPort('8080');
```

The code above isn't tested, but it should point you in the right direction.

/ Simon

**Comment by joyahm** [comment]
Thanks a lot, it works fine.

**Comment by joyahm** [comment]
Sorry for bothering you again, I can do everything via proxy settings with this class. but it break page instead of showing result.
as example: `$tinder->sendMessage($userId, $message);` send messages, I can see that on tinder.com. But script got break (blank page).

**Comment by skipperbent** [comment]
@joyahm 

No problem, you're welcome 😄 

The SDK should throw an exception if the response if not valid. But it can be many things - it all depends on how you've implemented your solution.

1. Check that the following entries exists in your `php.ini`. 
```
error_reporting=E_ALL
display_errors=On
``` 
2. You might also find some info about the error in your `php_errors.log`
3. Ensure that the curl-option for returning transfer is set properly (`CURLOPT_RETURNTRANSFER`).
4. If none of the above works you can try to dump the response object directly and check what response you are getting from Tinder (headers, http-codes etc).

```php
public function api($url = null, $method = self::METHOD_GET, array $data = [])
{
     // Dump the object - it contains the response, headers, http-codes etc...

     die(var_dump(parent::api($url, $method, $data)));

     return json_decode(parent::api($url, $method, $data)->getResponse());
}
```

/ Simon

**Comment by joyahm** [comment]
I'm extremely sorry for late, the error is:

`Parse error: syntax error, unexpected '?>', expecting function (T_FUNCTION) in /var/www/html/tinder/vendor/pecee/tinder-sdk/src/Pecee/Http/Service/Tinder.php on line 126`

thanks
